---

- hosts: all
  become: true
  tasks:


  - name: install apache & php packages for
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: install apache & php packages for Alma/Rocky
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Alma' or ansible_distribution == 'Rocky'
