---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_os_family == "Debian"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: install apache httpd package
    dnf:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: install php support for apache httpd
    dnf:
      name: php
      state: latest
    when: ansible_os_family == "RedHat"
