---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Alma/Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == 'Alma' or ansible_distribution == 'Rocky'

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

- hosts: web_servers
  become: true
  tasks:

  - name: install apache & php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install apache & php packages for Alma/Rocky
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'Alma' or ansible_distribution == 'Rocky'

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    apt:
      name:  mariadb-server
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install mariadb package (Alma/Rocky)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == 'Alma' or ansible_distribution == 'Rocky'

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

