---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (AlmaLinux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == 'AlmaLinux'

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'


- hosts: web_servers
  become: true
  tasks:

  - name: install apache & php packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install apache & php packages for AlmaLinux)
    tags: apache,https,alma,rocky
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'AlmaLinux'

  - name: copy default html file for site
    tags: apache,apahe2,htppd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: mariadb,db,ubuntu
    apt:
      name:  mariadb-server
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install mariadb package (AlmaLinux)
    tags: mariadb, db,alma,rocky
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == 'AlmaLinux'

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

