---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (AlmaLinux & RockyLinux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'Rocky'

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.10.4/terraform_1.10.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache & php packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install apache & php packages for AlmaLinux & RockyLinux)
    tags: apache,https,alma,rocky
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'Rocky'

  - name: copy default html file for site
    tags: apache,apahe2,htppd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: mariadb,db,ubuntu
    apt:
      name:  mariadb-server
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install mariadb package (AlmaLinux & RockyLinux)
    tags: mariadb, db,alma,rocky
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'Rocky'

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

