- name: install apache & php packages for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: install apache & php packages for AlmaLinux & RockyLinux
  tags: apache,httpd,AlmaLinux,Rocky
  dnf:
    name: 
      - httpd
      - php
    state: latest
  when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'Rocky'

- name: change e-mail address for admin
  tags: apache,httpd,AlmaLinux,Rocky
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net 
  when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'Rocky'
  register: httpd

- name: restart httpd for AltaLinux & RockLinux
  tags: apache,httpd,AlmaLinux,Rocky
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apahe2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start httpd (AlmaLinux & Rocky)
  tags: apache,apahe2,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'Rocky'
